### ISSUE TITLE
Follow a person

### ISSUE THREAD

**Issue by evanp** [swicg/activitypub-html-discovery#10]
"As a Web user, when viewing a profile page, I want to know the equivalent Person object, so I can Follow it."

**Comment by benpate** [comment]
I believe [FEP-3b86](http://w3id.org/fep/3b86) is a good solution to this use case.  To avoid spamming a huge comment on several issues, I added #15 as its own discussion.

Also: Many Fediverse servers already support "oStatus Remote Follows" which fulfills this use case.  Unfortunately, this standard has mostly been lost and the existing documentation/tutorials are hard to find.  

Republishing this standard might be a good start, but oStatus does not solve the larger, generalized problem, which is why I wrote FEP-3b86.
